@startuml urejanjeSeznamaOpravil
hide footbox

skinparam backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam actorBorderColor black
skinparam actorBackgroundColor white
skinparam arrowColor black  
skinparam sequenceLifeLineBorderColor #5FB8EC
skinparam sequenceParticipantBorderColor #5FB8EC
skinparam sequenceParticipantBackgroundColor white

actor "Prijavljeni uporabnik" as pup<<actor>>
participant ":GoogleCalendarWindow" as Vmesnik <<boundary>>
participant ":GoogleCalendarAdapter" as adapter <<control>>
participant ":GoogleCalendarAPI" as calendar <<External API>>

pup -> Vmesnik : //izbor ogleda\ndogodkov na koledarju\nshowCalendarTasks()
activate Vmesnik
Vmesnik -> adapter : getTasks(userid)
activate adapter
adapter -> calendar : list(calendarId)
activate calendar
calendar --> adapter : events[]
deactivate calendar
adapter --> Vmesnik : tasks[]
deactivate adapter
Vmesnik --> pup : //prikaz dogodkov\nna koledarju

