@startuml urejanjeSeznamaOpravil
hide footbox

skinparam backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam actorBorderColor black
skinparam actorBackgroundColor white
skinparam arrowColor black  
skinparam sequenceLifeLineBorderColor #5FB8EC
skinparam sequenceParticipantBorderColor #5FB8EC
skinparam sequenceParticipantBackgroundColor white

actor "Zunanji uporabnik" as zup<<actor>>
participant ":IssueReportWindow" as Vmesnik <<boundary>>
participant ":IssueReport" as report <<control>>



zup -> Vmesnik: // Izberi Poročanje\no nepravilnem delovanju

activate Vmesnik
zup <-- Vmesnik: // prikaz obrazca\nza vnos napake (naslov napake in opis)
zup -> Vmesnik: // Izpolnjen obrazec

Vmesnik -> report: //Odgovore obrazca preobrazimo v razred Issue\naddIssue(user, issue)
activate report


Vmesnik <-- report: //Potrjeno dodano poročilo
deactivate report
zup <-- Vmesnik: //prikaži potrdilo
deactivate Vmesnik

