''todo
@startuml urejanjeSeznamaOpravil
hide footbox

skinparam backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam actorBorderColor black
skinparam actorBackgroundColor white
skinparam arrowColor black  
skinparam sequenceLifeLineBorderColor #5FB8EC
skinparam sequenceParticipantBorderColor #5FB8EC
skinparam sequenceParticipantBackgroundColor white

actor "Prijavljeni porabnik" as pup<<actor>>
participant ":SearchUsersWindow" as Vmesnik <<boundary>>
participant ":SearchUsers" as search <<control>>
participant ":SignedUser" as signedUser <<entity>>



pup -> Vmesnik: // Izberi iskanje uporabnikov

activate Vmesnik
pup <-- Vmesnik: // prikaz iskalne vrstice
pup -> Vmesnik: // vnos v iskalno vrstico,\n izbere išči,\nshowUsers(name)
Vmesnik -> search: findUsers(name)
activate search
loop for each signedUser
search -> signedUser: signedUser.getName()
activate signedUser
signedUser --> search: ime
deactivate signedUser
end
search -> Vmesnik: // matchingUsers[]
deactivate search
Vmesnik -> pup: // prikaz ujemajočih uporabnikov
deactivate Vmesnik