@startuml Uporaba_casovnika

skinparam backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam arrowColor black
skinparam state {
  BackgroundColor white
  BorderColor #5FB8EC
  StartColor #5FB8EC
  EndColor #5FB8EC
}

state Idle

state Running

state Break

[*] -> Idle
Idle --> Running: start()
Running --> Break: startBreak()
Break --> Running: stopBreak()
Running --> Idle: reset()
Break --> Idle: reset()

Idle -right-> [*]: izhod


@enduml
