@startuml urejanjeSeznamaOpravil
hide footbox

skinparam backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam actorBorderColor black
skinparam actorBackgroundColor white
skinparam arrowColor black  
skinparam sequenceLifeLineBorderColor #5FB8EC
skinparam sequenceParticipantBorderColor #5FB8EC
skinparam sequenceParticipantBackgroundColor white

actor "Admin" as admin<<actor>>
participant ":ManageEmployeesWindow" as Vmesnik <<boundary>>
participant ":ManageEmployees" as manage <<control>>
participant ":Developer" as dev <<entity>>


admin -> Vmesnik: // Izberi upravljanje\nračunov zaposlenih

activate Vmesnik
admin <-- Vmesnik: // prikaz obrazca\nza ustvarjanje novega računa
admin -> Vmesnik: // Izpolnjen obrazec\nklilk na gumb "Vnesi"
Vmesnik -> Vmesnik: // preveri pravilnost\nvnosa podatkov
Vmesnik -> manage: // če je vnos ok:\naddEmployee(ime, priimek, email, geslo)
activate manage
manage -> dev: //Ustvarimo nov objekt razreda Developer
activate dev
alt brez napake
dev --> manage:// potrdilo o dodajanju
Vmesnik <-- manage: //Potrdilo o dodajanju
admin <-- Vmesnik: //prikaži potrdilo
else izjemni tok: napaka - uporabnik že obstaja
dev --> manage:// napaka - uporabnik že obstaja
deactivate dev
Vmesnik <-- manage: //Napaka - uporabnik že obstaja
deactivate manage
admin <-- Vmesnik: //prikaži napako
deactivate Vmesnik
end
