@startuml urejanjeSeznamaOpravil
hide footbox

skinparam backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam actorBorderColor black
skinparam actorBackgroundColor white
skinparam arrowColor black  
skinparam sequenceLifeLineBorderColor #5FB8EC
skinparam sequenceParticipantBorderColor #5FB8EC
skinparam sequenceParticipantBackgroundColor white

actor "Razvijalec" as dev<<actor>>
participant ":IssueReportWindow" as Vmesnik <<boundary>>
participant ":IssueReport" as report <<control>>
participant ":Issue" as issue <<entity>>

dev -> Vmesnik: // Izberi pregled poročanih\n nepravilnih delovanj\nshowUnsolvedIssues()
activate dev
activate Vmesnik

Vmesnik -> report: getUnsolvedIssues()
activate report

Vmesnik <-- report: //UnsolvedIssues[]
deactivate report
dev <-- Vmesnik: // prikaz seznama nerešenih poročil
deactivate Vmesnik
deactivate dev


Vmesnik -> report: rejectIssue(issue)
activate Vmesnik
activate report
report -> issue:// delete Issue
activate issue
report <-- issue: //issue removed
Vmesnik <-- report: //issue removed
deactivate report
deactivate issue

Vmesnik -> Vmesnik: showUnsolvedIssues()
dev <-- Vmesnik: // changes made,\nprikaz seznama nerešenih poročil
activate dev
''tale je alternativni tok
