@startuml
skinparam backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam usecase {
  backgroundColor white
  borderColor #5FB8EC
  arrowColor black
}
skinparam actorBorderColor black
skinparam actorBackgroundColor white

left to right direction

actor "Zunanji \nuporabnik" AS ZU
actor "Prijavljeni \nuporabnik" AS PRUp
actor "Neprijavljeni \nuporabnik" AS NPU
actor "Administrator" AS ADMIN
actor "Analitik" AS ANAL
actor "Razvijalec" AS DEV
actor "Zunanji\nsistem" AS S1
note right of S1 : Sistem ki \ndostopa do \nnašega APIja.
actor "Google \nCalendar" AS GOOG

rectangle "Aplikacija produktivnosti in organizacije" {
  usecase "Uporaba \nčasovnika" AS PU1
  usecase "Konfiguriranje \nčasovnika" AS PU2
  usecase "Prijava in \nodjava" AS PU3
  usecase "Ogled aktivnosti \nsledilcev" AS PU4
  usecase "Upravljanje računov \nzaposlenih" AS PU5
  usecase "Urejanje seznama \nopravil" AS PU6
  usecase "Sledenje \nuporabnikov" AS PU7
  usecase "Iskanje \nuporabnikov" AS PU8
  usecase "Ogled zaslona \nproduktivnosti" AS PU9
  usecase "Poročanje o nepravilnem \ndelovanju" AS PU10
  usecase "Ogled dodgodkov\nna koledarju" AS PU11
  usecase "Upravljanje dogodkov \nna koledarju" AS PU12
  usecase "Upravljanje poročanih \nnepravilnih delovanj" AS PU13
  usecase "Shranjevanje podatkov \no aktivnostih uporabnikov \nza analitiko" AS PU14
  usecase "Izboljšanje \nproduktivnosti" AS PU15
}

PRUp ---|> ZU
NPU -left-|> ZU

DEV --> (PU13)
ANAL --> (PU14)
ADMIN --> (PU5)

PRUp -> (PU4)
PRUp --> (PU11)
PRUp -> (PU7)
PRUp -> (PU9)
PRUp -> (PU3)

ZU -right-> (PU15)
ZU ---> (PU10)

S1 -up-> (PU6)
(PU11) ---> GOOG

(PU7) ..> (PU8) : include
(PU11) .up.> (PU12) : extends
(PU2) ..> (PU1) : extends

(PU1) -down-|> (PU15)
(PU6) -|> (PU15)
@enduml
