@startuml komponentni_diagram
skinparam backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam ArrowColor black
skinparam component {
  backgroundcolor #e8f5fd
  bordercolor #5FB8EC
}
skinparam interface {
  backgroundcolor #e8f5fd
  bordercolor #5FB8EC
}

interface "Vmesnik za bazo podatkov" as V1
interface "HTTP" as V2
interface "Vmesnik za Google koledar" as V3
interface "Vmesnik za podatkovno skladišče" as V4

component "**Baza podatkov**" as B <<component>>

component "**Podatkovno skladišče**" as PS <<component>>

component "**Google koledar**" as GK <<component>>

skinparam componentStyle rectangle

component "**Arhitektura strežnik/odjemlec**" as SC{
  component "**Aplikacija produktivnosti in organizacije (Web App)**" as A  <<component>>{
  }

  component "**Web Server**" as WS <<component>> 
}

A --( V2
V2 -- WS
WS --( V1
V1 -- B
WS --( V3
V3 -- GK
WS --( V4
V4 -- PS
@enduml
