@startuml paketni_diagram

skinparam backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam ArrowColor black
skinparam package {
  backgroundcolor #e8f5fd
  backgroundcolor<<subsystem>> white
  bordercolor #5FB8EC
}

package Aplikacija <<system>> {
    package MVC <<layer>> {
        package View <<user interface>> {
        }
        package Controller <<controller>> {
        }
    }
    package Časovnik <<subsystem>> {
        package UporabaČasovnika
        package Opomnik
    }
    package SeznamOpravil <<subsystem>> {
        package UrejanjeOpravil
    }
    package DogodkiNaKoledarju <<subsystem>> {
        package UporabiKoledar
    }
    package PoročanjeNepravilnosti <<subsystem>> {
        package VnosNepravilnosti
        package PreverjanjeNepravilnosti
    }
    package IskanjeUporabnikov <<subsystem>> {
          package DodajUporabnika
    }
}
package PodatkovnaBaza <<database>> {
    package database.json
}
package PodatkovnoSkladišče <<data warehouse>> {
    package warehouse.json
}
package GoogleCalendar <<external>> {
    package GoogleCalendarAPI
}

MVC .down.> PodatkovnaBaza
MVC .down.> PodatkovnoSkladišče
PodatkovnaBaza .down.> PodatkovnoSkladišče : cevovod

View .down.> Controller : <<send requests>>
Controller .down.> View : <<renders>>

UrejanjeOpravil .down.> Časovnik
UporabaČasovnika .down.> Opomnik
UporabiKoledar .down.> GoogleCalendarAPI
@enduml