@startuml "PERT diagram"

skinparam backgroundColor transparent
left to right direction

scale 0.8

<style>
stateDiagram {
  arrow {
    LineColor black
  }
}
</style>

skinparam State {
  BackgroundColor #e8f5fd
  BorderColor #5FB8EC
}

skinparam defaultTextAlignment center

state "Izbira ustrezne arhitekture (A1)" as A1 : <#e8f5fd,#e8f5fd>|  0,25 | 0 | 0,25 |\n|  0,125 | 0,125 | 0,375 |
state "<color:darkred>Izbira izgleda aplikacije (A2)</color>" as A2 #ffe6e6;line:darkred : <#ffe6e6,#ffe6e6>| 0,375 | 0 | 0,375 |\n| 0 | 0 | 0,375 |
state "<color:darkred>Določitev uporabniških vlog (A3)</color>" as A3 #ffe6e6;line:darkred : <#ffe6e6,#ffe6e6>| 0,25 | 0 | 0,25 |\n|   0 | 0 | 0,25 |
state "Načrtovanje transakcijske baze (A4)" as A4 #ffe6e6;line:darkred : <#ffe6e6,#ffe6e6>| 0,25 | 0,25 | 0,5 |\n|  0 | 0,25 | 0,5 |
state "Načrtovanje podatkovnega skladišča (A5)" as A5 : <#e8f5fd,#e8f5fd>|  0,25 | 0 | 0,25 |\n|  0,25 | 0,25 | 0,5 |
state "Izdelava zaslonskih mask (A6)" as A6 #ffe6e6;line:darkred : <#ffe6e6,#ffe6e6>|   0,5 | 0,375 | 0,875 |\n|   0 | 0,375 | 0,875 |
state "Izdelava transakcijske baze (A7)" as A7 #ffe6e6;line:darkred : <#ffe6e6,#ffe6e6>|   0,375 | 0,5 | 0,875 |\n|   0 | 0,5 | 0,875 |
state "Izdelava podatkovnega skladišča (A8)" as A8 : <#e8f5fd,#e8f5fd>|   0,375 | 0,25 | 0,625 |\n|   0,25 | 0,5 | 0,875 |
state "Implementacija prijave in registracije (A9)" as A9 : <#e8f5fd,#e8f5fd>|   0,375 | 0,875 | 1,25 |\n|   0,125 | 1 | 1,375 |
state "Implementacija obnovitve pozabljenega gesla (A10)" as A10 : <#e8f5fd,#e8f5fd>|   0,375 | 1,25 | 1,625 |\n|   0,125 | 1,375 | 1,75 |
state "Implementacija iskanja prijateljev (A11)" as A11 : <#e8f5fd,#e8f5fd>|   0,5 | 0,875 | 1,375 |\n|   0,375 | 1,25 | 1,75 |
state "Implementacija shranjevanja dogodkov uporabnika (A12)" as A12 : <#e8f5fd,#e8f5fd>|   0,375 | 0,875 | 1,25 |\n|   0,5 | 1,375 | 1,75 |
state "Implementacija vmesnika določanja navad (A13)" as A13 : <#e8f5fd,#e8f5fd>|   0,125 | 0,875 | 1 |\n|   0,75 | 1,625 | 1,75 |
state "Implementacija časovnika in njegovega urejanja (A14)" as A14 : <#e8f5fd,#e8f5fd>|   0,375 | 0,875 | 1,25 |\n|   0,5 | 1,375 | 1,75 |
state "Implementacija Google koledarja preko API-ja (A15)" as A15 #ffe6e6;line:darkred : <#ffe6e6,#ffe6e6>|   0,375 | 0,875 | 1,25 |\n| 0 | 0,875 | 1,25 |
state "Implementacija urejanja dogodkov na Google koledarju (A16)" as A16 #ffe6e6;line:darkred : <#ffe6e6,#ffe6e6>|   0,5 | 1,25 | 1,75 |\n| 0 | 1,25 | 1,75 |
state "Implementacija beleženja aktivnosti in prenosa\niz transakcijske baze v podatkovno skladišče (A17)" as A17 #ffe6e6;line:darkred : <#ffe6e6,#ffe6e6>|   0,25 | 0,875 | 1,125 |\n|   0 | 0,875 | 1,125 |
state "Implementacija grafičnega prikaza statistik\nuporabnika in njegovih prijateljev (A18)" as A18 : <#e8f5fd,#e8f5fd>|   0,375 | 1,125 | 1,5 |\n|   0,25 | 1,375 | 1,75 |
state "Implementacija ogleda aktivnosti prijateljev (A19)" as A19 #ffe6e6;line:darkred : <#ffe6e6,#ffe6e6>|   0,625 | 1,125 | 1,75 |\n|   0 | 1,125 | 1,75 |
state "Implementacija urejanja uporabniškega računa (A20)" as A20 : <#e8f5fd,#e8f5fd>|   0,25 | 0,875 | 1,125 |\n|   0,625 | 1,5 | 1,75 |
state "Implementacija vmesnika za poročanje o napakah (A21)" as A21 : <#e8f5fd,#e8f5fd>|   0,5 | 0,875 | 1,375 |\n|   0,375 | 1,25 | 1,75 |
state "Implementacija vmesnika za upravljanje\nporočil o nepravilnem delovanju (A22)" as A22 : <#e8f5fd,#e8f5fd>|   0,5 | 0,875 | 1,375 |\n|   0,375 | 1,25 | 1,75 |
state "Upravljanje projekta (A23)" as A23 : <#e8f5fd,#e8f5fd>| 1,25 | 0 | 1,25 |\n|   0,5 | 0,5 | 1,75 |

[*] -[#darkred,bold]-> A1
[*] -[#darkred,bold]-> A2
[*] -[#darkred,bold]-> A3
[*] -[#darkred,bold]-> A5

A3-> A4

A1 --> A6
A2 --> A6

A1 --> A7
A4 --> A7

A1 --> A8
A5 --> A8

A6 --> A9
A7 --> A9

A9 --> A10

A6 --> A11
A7 --> A11

A7 --> A12

A6 --> A13
A7 --> A13

A6 --> A14

A6 --> A15

A15 --> A16

A7 --> A17
A8 --> A17

A6 --> A18
A17 --> A18

A6 --> A19
A17 --> A19

A6 --> A20
A7 --> A20

A6 --> A21
A7 --> A21

A6 --> A22
A7 --> A22

[*] -[#darkred,bold]-> A23

'A3 --> [*]
'A23 --> [*]
'A14 --> [*]
'A13 --> [*]
'A20 --> [*]
'A21 --> [*]
'A1 --> A2
'A1 -[#darkred,bold]-> A3
'A2 --> [*]
'A3 -[#darkred,bold]-> [*]

@enduml
