@startuml "PERT diagram"

skinparam backgroundColor transparent
left to right direction

scale 0.8

<style>
stateDiagram {
  arrow {
    LineColor black
  }
}
</style>

skinparam State {
  BackgroundColor #e8f5fd
  BorderColor #5FB8EC
}

skinparam defaultTextAlignment center

state "<color:darkred>Dolocitev funkcionalnih in nefunkcionalnih zahtev (A1)</color>" as A1 #ffe6e6;line:darkred : <#ffe6e6,#ffe6e6>|  0,25 | 0 | 0,25 |\n|  0 | 0 | 0,25 |
state "Izbira ustrezne arhitekture (A2)" as A2 : <#e8f5fd,#e8f5fd>|  0,125 | 0,25 | 0,375 |\n|  0,25 | 0,5 | 0,625 |
state "Izbira izgleda aplikacije (A3)</color>" as A3 : <#e8f5fd,#e8f5fd>|  0,375 | 0,25 | 0,625 |\n|  0,125 | 0,375 | 0,75 |
state "<color:darkred>Določitev uporabniških vlog (A4)</color>" as A4 #ffe6e6;line:darkred : <#ffe6e6,#ffe6e6>|  0,125 | 0,25 | 0,375 |\n|  0 | 0,25 | 0,375 |
state "<color:darkred>Načrtovanje transakcijske baze (A5)</color>" as A5 #ffe6e6;line:darkred : <#ffe6e6,#ffe6e6>|  0,25 | 0,375 | 0,625 |\n|  0 | 0,375 | 0,625 |
state "Načrtovanje podatkovnega skladišča (A6)" as A6 : <#e8f5fd,#e8f5fd>|  0,25 | 0 | 0,25 |\n|  0,375 | 0,375 | 0,625 |
state "Izdelava zaslonskih mask (A7)" as A7 : <#e8f5fd,#e8f5fd>|  0,5 | 0,625 | 1,125 |\n|  0,125 | 0,75 | 1,25 |
state "<color:darkred>Izdelava transakcijske baze (A8)</color>" as A8 #ffe6e6;line:darkred : <#ffe6e6,#ffe6e6>|  0,375 | 0,625 | 1 |\n|  0 | 0,625 | 1 |
state "Izdelava podatkovnega skladišča (A9)" as A9 : <#e8f5fd,#e8f5fd>|  0,375 | 0,375 | 0,75 |\n|  0,25 | 0,625 | 1 |
state "Implementacija prijave in registracije (A10)" as A10 : <#e8f5fd,#e8f5fd>|  0,375 | 1,125 | 1,5 |\n|  0,25 | 1,375 | 1,75 |
state "Implementacija obnovitve pozabljenega gesla (A11)" as A11 : <#e8f5fd,#e8f5fd>|  0,25 | 1,5 | 1,75 |\n|  0,25 | 1,75 | 2 |
state "Implementacija iskanja prijateljev (A12)" as A12 : <#e8f5fd,#e8f5fd>|  0,375 | 1,125 | 1,5 |\n|  0,5 | 1,625 | 2 |
state "Implementacija shranjevanja dogodkov uporabnika (A13)" as A13 : <#e8f5fd,#e8f5fd>|  0,125 | 1 | 1,125 |\n|  0,875 | 1,875 | 2 |
state "Implementacija vmesnika določanja navad (A14)" as A14 : <#e8f5fd,#e8f5fd>|  0,375 | 1,125 | 1,5 |\n|  0,5 | 1,625 | 2 |
state "Implementacija časovnika in njegovega urejanja (A15)" as A15 : <#e8f5fd,#e8f5fd>|  0,375 | 1,125 | 1,5 |\n|  0,5 | 1,625 | 2 |
state "Implementacija Google koledarja preko API-ja (A16)" as A16 : <#e8f5fd,#e8f5fd>|  0,5 | 1,125 | 1,625 |\n|  0,125 | 1,25 | 1,75 |
state "Implementacija urejanja dogodkov na Google koledarju (A17)" as A17 : <#e8f5fd,#e8f5fd>|  0,25 | 1,625 | 1,875 |\n|  0,125 | 1,75 | 2 |
state "<color:darkred>Implementacija beleženja aktivnosti in prenosa</color>\n<color:darkred>iz transakcijske baze v podatkovno skladišče (A18)</color>" as A18 #ffe6e6;line:darkred : <#ffe6e6,#ffe6e6>|  0,375 | 1 | 1,375 |\n|  0 | 1 | 1,375 |
state "<color:darkred>Implementacija grafičnega prikaza statistik</color>\n<color:darkred>uporabnika in njegovih prijateljev (A19)</color>" as A19 #ffe6e6;line:darkred : <#ffe6e6,#ffe6e6>|  0,625 | 1,375 | 2 |\n|  0 | 1,375 | 2 |
state "Implementacija ogleda aktivnosti prijateljev (A20)" as A20 : <#e8f5fd,#e8f5fd>|  0,25 | 1,375 | 1,625 |\n|  0,375 | 1,75 | 2 |
state "Implementacija urejanja uporabniškega računa (A21)" as A21 : <#e8f5fd,#e8f5fd>|  0,375 | 1,125 | 1,5 |\n|  0,5 | 1,625 | 2 |
state "Implementacija vmesnika za poročanje o napakah (A22)" as A22 : <#e8f5fd,#e8f5fd>|  0,5 | 1,125 | 1,625 |\n|  0,375 | 1,5 | 2 |
state "Implementacija vmesnika za upravljanje\nporočil o nepravilnem delovanju (A23)" as A23 : <#e8f5fd,#e8f5fd>|  0,5 | 1,125 | 1,625 |\n|  0,375 | 1,5 | 2 |
state "Upravljanje projekta (A24)" as A24 : <#e8f5fd,#e8f5fd>|  1,25 | 0 | 1,25 |\n|  0,75 | 0,75 | 2 |

[*] -[#darkred,bold]-> A1
[*] -[#darkred,bold]-> A6
[*] -[#darkred,bold]-> A24

A1 -> A2
A1 -> A3
A1 -> A4

A4-> A5

A2 --> A7
A3 --> A7

A2 --> A8
A5 --> A8

A2 --> A9
A6 --> A9

A7 --> A10
A8 --> A10

A10 --> A11

A7 --> A12
A8 --> A12

A8 --> A13

A7 --> A14
A8 --> A14

A7 --> A15

A7 --> A16

A16 --> A17

A8 --> A18
A9 --> A18

A7 --> A19
A18 --> A19

A7 --> A20
A18 --> A20

A7 --> A21
A8 --> A21

A7 --> A22
A8 --> A22

A7 --> A23
A8 --> A23



@enduml
